const KEY='radarProductosGanadores_v2';let products=JSON.parse(localStorage.getItem(KEY)||'[]');
const $=id=>document.getElementById(id), modal=$('modal'), form=$('form');
function save(){localStorage.setItem(KEY,JSON.stringify(products));render()}
function safe(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function link(url,label){return url?`<a href="${safe(url)}" target="_blank" rel="noopener">${label} ↗</a>`:''}
function render(){let q=$('search').value.toLowerCase(),f=$('filter').value;let list=products.filter(p=>(!f||p.status===f)&&[p.name,p.niche,p.country].join(' ').toLowerCase().includes(q));$('total').textContent=products.length;$('modelar').textContent=products.filter(p=>p.status==='Para modelar').length;$('revisar').textContent=products.filter(p=>p.status==='Revisar').length;$('descartar').textContent=products.filter(p=>p.status==='Descartar').length;$('empty').style.display=products.length?'none':'block';$('cards').innerHTML=list.map(p=>`<article class="card"><div class="cardTop"><div><div class="meta">${safe(p.niche||'Sin nicho')} ${p.country?'• '+safe(p.country):''}</div><h3>${safe(p.name)}</h3><div class="meta">${safe(p.price||'Precio no cargado')} ${p.ads!==''?'• '+safe(p.ads)+' anuncios activos':''}</div></div><span class="badge ${p.status==='Para modelar'?'modelar':p.status==='Descartar'?'descartar':''}">${safe(p.status)}</span></div><div class="links">${link(p.fanpage,'Fanpage')}${link(p.library,'Biblioteca')}${link(p.sales,'Página de venta')}</div>${p.notes?`<div class="notes">${safe(p.notes)}</div>`:''}<div class="cardActions"><button class="ghost mini" onclick="editProduct('${p.id}')">Editar</button><button class="mini danger" onclick="deleteProduct('${p.id}')">Eliminar</button></div></article>`).join('')}
function openNew(){form.reset();$('id').value='';$('status').value='Revisar';$('date').value=new Date().toISOString().slice(0,10);$('modalTitle').textContent='Agregar producto';modal.showModal()}
window.editProduct=id=>{let p=products.find(x=>x.id===id);if(!p)return;['id','name','niche','country','price','ads','fanpage','library','sales','status','date','notes'].forEach(k=>$(k).value=p[k]??'');$('modalTitle').textContent='Editar producto';modal.showModal()};
window.deleteProduct=id=>{if(confirm('¿Eliminar este producto del radar?')){products=products.filter(p=>p.id!==id);save()}};
form.addEventListener('submit',e=>{e.preventDefault();if(!$('name').value.trim())return;let obj={};['id','name','niche','country','price','ads','fanpage','library','sales','status','date','notes'].forEach(k=>obj[k]=$(k).value.trim());if(!obj.id)obj.id=crypto.randomUUID?crypto.randomUUID():Date.now().toString();let i=products.findIndex(p=>p.id===obj.id);i>=0?products[i]=obj:products.unshift(obj);save();modal.close()});
$('newBtn').onclick=$('emptyBtn').onclick=openNew;$('closeBtn').onclick=$('cancelBtn').onclick=()=>modal.close();$('search').oninput=$('filter').onchange=render;
$('exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify(products,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='radar-productos-respaldo.json';a.click();URL.revokeObjectURL(a.href)};
$('importFile').onchange=async e=>{try{let data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data))throw 0;if(confirm(`¿Importar ${data.length} productos? Esto reemplazará los datos actuales.`)){products=data;save()}}catch{alert('El archivo de respaldo no es válido.')}e.target.value=''};render();
